# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0004_auto_20170911_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clooset',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='clooset',
            unique_together=set([('user', 'product')]),
        ),
    ]
