# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20170912_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clooset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cloosets', to='models.Product'),
        ),
    ]
