branch-defaults:
  default:
    environment: social-commerce-dev
    group_suffix: null
global:
  application_name: social_commerce
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
